[variables]
NODE_ENV = "production"
PORT = "3000"
NIXPACKS_SPA_CADDY = "false"
NIXPACKS_NO_CADDY = "true"

[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmd = "npm ci"

[phases.build]
cmd = "npm run build && cd dist && sed -i 's/import\\.meta\\.dirname/__dirname/g' index.js && sed -i '1i\\// Define __dirname for ES modules\nimport { fileURLToPath } from \"url\";\nimport { dirname } from \"path\";\nconst __filename = fileURLToPath(import.meta.url);\nconst __dirname = dirname(__filename);\n' index.js"

[start]
cmd = "npm start"