[variables]
NODE_ENV = "production"
PORT = "3000"
NIXPACKS_SPA_CADDY = "false"
NIXPACKS_NO_CADDY = "true"

[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmd = "npm ci"

[phases.build]
cmd = "npm run build && cd dist && sed 's/import\\.meta\\.dirname/__dirname/g' index.js > index.js.tmp && mv index.js.tmp index.js"

[start]
cmd = "npm start"